package com.yatra.payment.ui.enums;

public enum FailureCode {

	NO_FAILURE_CAPTURED(null),
	PAGE_LOAD_REQUEST_PARAMS_VALIDATION_FAILED("PAGE_LOAD_REQUEST_PARAMS_VALIDATION_FAILED"),

	FETCH_CREDITPOOL_BALANCE_EXCEPTION("FETCH_CREDITPOOL_BALANCE_EXCEPTION"),
	FETCH_CREDITPOOL_BALANCE_INVALID_RESPONSE_CODE("FETCH_CREDITPOOL_BALANCE_INVALID_RESPONSE_CODE"),

    FETCH_CORPORATE_USER_DETAILS_EXCEPTION("FETCH_CORPORATE_USER_DETAILS_EXCEPTION"),
	FETCH_CORPORATE_USER_DETAILS_INVALID_RESPONSE_CODE("FETCH_CORPORATE_USER_DETAILS_INVALID_RESPONSE_CODE"),
    
    FETCH_CORPORATE_CREDITPOOL_BALANCE_EXCEPTION("FETCH_CORPORATE_CREDITPOOL_BALANCE_EXCEPTION"),
	FETCH_CORPORATE_CREDITPOOL_BALANCE_INVALID_RESPONSE_CODE("FETCH_CORPORATE_CREDITPOOL_BALANCE_INVALID_RESPONSE_CODE"),
    
	FETCH_AGENT_PAYMENT_OPTIONS_EXCEPTION("FETCH_AGENT_PAYMENT_OPTIONS_EXCEPTION"),
	FETCH_AGENT_PAYMENT_OPTIONS_EMPTY("FETCH_AGENT_PAYMENT_OPTIONS_EMPTY"),
	FETCH_AGENT_PAYMENT_OPTIONS_INVALID_RESPONSE_CODE("FETCH_AGENT_PAYMENT_OPTIONS_INVALID_RESPONSE_CODE"),
	FETCH_CRP_PAYMENT_OPTIONS_NOT_AVAILABLE("FETCH_CRP_PAYMENT_OPTIONS_NOT_AVAILABLE"),
	FETCH_CRP_PAYMENT_OPTIONS_BOOKING_TYPE_NOT_AVAILABLE("FETCH_CRP_PAYMENT_OPTIONS_BOOKING_TYPE_NOT_AVAILABLE"),

	FETCH_CORPORATE_CARDS_EXCEPTION("FETCH_CORPORATE_CARDS_EXCEPTION"),
	FETCH_CORPORATE_CARDS_FAILURE_STATUS("FETCH_CORPORATE_CARDS_FAILURE_STATUS"),

	GET_QB_CARDS_REQUEST_INVALID("GET_QB_CARDS_REQUEST_INVALID"),
	FETCH_QB_CARDS_EXCEPTION("FETCH_QB_CARDS_EXCEPTION"),
	POPULATE_QB_CARDS_EXCEPTION("POPULATE_QB_CARDS_EXCEPTION"),
	CREATE_DEFAULT_QB_BEAN_FAILED("CREATE_DEFAULT_QB_BEAN_FAILED"),
	QB_PAYOP_NOT_ENABLED("QB_PAYOP_NOT_ENABLED"),

	FETCH_DCPIN_CONFIG_DETAILS_EXCEPTION("FETCH_DCPIN_CONFIG_DETAILS_EXCEPTION"),

	FETCH_ITINERARY_INVALID_RESPONSE("FETCH_ITINERARY_INVALID_RESPONSE"),
	FETCH_ITINERARY_EMPTY_RESPONSE("FETCH_ITINERARY_EMPTY_RESPONSE"),
	FETCH_ITINERARY_FAIL_RESPONSE("FETCH_ITINERARY_FAIL_RESPONSE"),
	FETCH_ITINERARY_REQUIRED_PARAMS_MISSING("FETCH_ITINERARY_REQUIRED_PARAMS_MISSING"),
	FETCH_ITINERARY_EXCEPTION("FETCH_ITINERARY_EXCEPTION"),

	VALIDATION_FROM_LOB_INVALID_RESPONSE("VALIDATION_FROM_LOB_INVALID_RESPONSE"),
	VALIDATION_FROM_LOB_EMPTY_RESPONSE("VALIDATION_FROM_LOB_EMPTY_RESPONSE"),
	VALIDATION_FROM_LOB_FAIL_RESPONSE("VALIDATION_FROM_LOB_FAIL_RESPONSE"),
	VALIDATION_FROM_LOB_PROMO_FAILED("VALIDATION_FROM_LOB_PROMO_FAILED"),
	VALIDATION_FROM_LOB_REQUIRED_PARAMS_MISSING("VALIDATION_FROM_LOB_REQUIRED_PARAMS_MISSING"),
	VALIDATION_FROM_LOB_EXCEPTION("VALIDATION_FROM_LOB_EXCEPTION"),

	WALLET_AUTH_FAILED("WALLET_AUTH_FAILED"), 
	WALLET_HANDSHAKE_FAILED("WALLET_HANDSHAKE_FAILED"), 
	WALLET_CAPTURE_FAILED("WALLET_CAPTURE_FAILED"),
	WALLET_AUTH_EXCEPTION("WALLET_AUTH_EXCEPTION"),
	WALLET_REVERSE_AUTH_EXCEPTION("WALLET_REVERSE_AUTH_EXCEPTION"),

	GENERIC_EXCEPTION("GENERIC_EXCEPTION"),
	SAVE_PASSSTHROUGH_CARD_EXCEPTION("SAVE_PASSSTHROUGH_CARD_EXCEPTION"),
	SAVE_IMPORTPNR_CARD_EXCEPTION("SAVE_IMPORTPNR_CARD_EXCEPTION"),
	SAVE_IMPORTPNR_INTERNATIONAL_CARD_EXCEPTION("SAVE_IMPORTPNR_CARD_EXCEPTION"),
	SAVE_GUEST_USER_CARD_EXCEPTION("SAVE_GUEST_USER_CARD_EXCEPTION"),
	SAVE_CARD_IN_SESSION_EXCEPTION("SAVE_CARD_IN_SESSION_EXCEPTION"),
	DO_INIT_PAYMENT_EXCEPTION("DO_INIT_PAYMENT_EXCEPTION"),
	INVALID_USER_ERROR_MESSAGE("INVALID_USER_ERROR_MESSAGE"),
	FAILED_TO_GET_PAYMENT_OPTION_PARAMETER("FAILED_TO_GET_PAYMENT_OPTION_PARAMETER"),
	
	B2B_USER_PROFILE_SERVICE_FAIL_RESPONSE("B2B_USER_PROFILE_SERVICE_FAIL_RESPONSE"),
	B2B_USER_PROFILE_SERVICE_EMPTY_RESPONSE("B2B_USER_PROFILE_SERVICE_FAIL_RESPONSE"),
	B2B_USER_PROFILE_SERVICE_INVALID_RESPONSE("B2B_USER_PROFILE_SERVICE_FAIL_RESPONSE"),
	B2B_USER_PROFILE_SERVICE_EXCEPTION("B2B_USER_PROFILE_SERVICE_FAIL_RESPONSE"),

	GET_BIN_DETAILS_API_INVALID_CARD_NUMBER("GET_BIN_DETAILS_API_INVALID_CARD_NUMBER"),
	VALIDATE_EMI_CARD_BANK_API_INVALID_CARD_NUMBER("VALIDATE_EMI_CARD_BANK_API_INVALID_CARD_NUMBER"),
	FETCH_BIN_DETAILS_FAILED("FETCH_BIN_DETAILS_FAILED"),
	
	GV_VALIDATE_EXCEPTION("GV_VALIDATE_EXCEPTION"),
	GV_VALIDATE_FAILURE("GV_VALIDATE_FAILURE"),
	GV_VALIDATE_PAYOP_NOT_ENABLED("GV_VALIDATE_PAYOP_NOT_ENABLED"),
	GV_FRAUD_CHECK_ENABLED("GV_FRAUD_CHECK_ENABLED"),
	
	GV_UNBLOCK_EXCEPTION("GV_UNBLOCK_EXCEPTION"),
	GV_UNBLOCK_FAILURE("GV_UNBLOCK_FAILURE"),
	GV_UNBLOCK_PAYOP_NOT_ENABLED("GV_UNBLOCK_PAYOP_NOT_ENABLED"),
	
	GV_REDEEM_EXCEPTION("GV_REDEEM_EXCEPTION"),
	GV_REDEEM_FAILURE("GV_REDEEM_FAILURE"),
	GV_REDEEM_PAYOP_NOT_ENABLED("GV_REDEEM_PAYOP_NOT_ENABLED"),
	
	IXIGO_MONEY_REDEEM_EXCEPTION("IXIGO_MONEY_REDEEM_EXCEPTION"),
        
	NO_COST_EMI_EXCEPTION("NO_COST_EMI_EXCEPTION"),
	
	NO_COST_EMI_AMOUNT_MISMATCH("Failure due to NO COST EMI Amount Mismatch"),
	BOOKINGDOTCOM_ERROR("BOOKINGDOTCOM_ERROR"),
	PRIVY_FLOW_ERROR("PRIVY_FLOW_ERROR"),
	USER_NOT_ELIGIBLE_FOR_REWARDS("USER_NOT_ELIGIBLE_FOR_REWARDS"),
	PASSTHROUGH_SAVE_CARD_TEMPORARILY_FAILURE("PASSTHROUGH_SAVE_CARD_TEMPORARILY_FAILURE");
	
	private String code;

	private FailureCode(String code) {
		this.code = code;
	}

	public String getCode() {
		return this.code;
	}
	
	public FailureCode setCustomCode(String customCode) {
		if(this.code == null)
			this.code = customCode;
		else
			this.code = this.toString() + ':' + customCode;
		return this;
	}
	
}
