package com.yatra.payment.ui.enums;

public enum ResponseDecisionScenarios {
	EWALLET_HANDSHAKE_FAILURE,
	VALIDATION_FAILURE_WITH_REDIRECT,
	VALIDATION_FAILURE_WITHOUT_REDIRECT,
	GENERIC_ERROR,
	COMPLETE_WALLET_SUCCESS,
	COMPLETE_VOUCHER_SUCCESS,
	VOUCHER_VALIDATION_FAILURE,
	SUCESS_REDIRECT_TO_PORTAL,
	SUCESS_AJAX_TO_PORTAL,
	COMPLETE_GV_PAYMENT_FAILURE,
	COMPLETE_WALLET_FAILURE,
	COMPLETE_IXIGO_PAYMENT_FAILURE,
	COMPLETE_IXIGO_PAYMENT_SUCCESS,
	BOOKINGDOTCOM_ERROR,
	PRIVY_FLOW_ERROR,
	USER_NOT_ELIGIBLE_FOR_REWARDS,
	PASSTHROUGH_FLOW_SAVE_CARD_TEMPORARILY_FAILURE,
	CARD_NOT_ELIGIBLE_FOR_PAYMENT;
}
